### ISSUE TITLE
Error if associating Investigation to Publication in FAIRDOMHub

### ISSUE THREAD

**Issue by OlgaKrebs** [seek4science/seek#405] opened 2020-07-27 12:41 UTC
Creating new Investigation  https://fairdomhub.org/investigations/407   I defined publication https://fairdomhub.org/publications/414 to be linked to this Investigation and got error message (see screen shot attached) “invalid publication”  . To be able to finish creating Investigation, I removed link to publication, finished creating Investigation and opened same publication to manage and to associate same investigation – got error message saying “ you have to define publication type” – so different error message to that I got trying to associate Investigation to registered publication. I defined publication type and could finish without error. BUT: I still can’t see association to publication on Investigation page – neither on the ISA graph nor in the related items list. Same for Publication page – no association/relation shown. If I open publication to manage - associated Investigation is shown (screen shot2)

I assume , this publication has been registered before we had “publication type” , but there is no solution for this bug.

**Comment by OlgaKrebs** [comment] 2020-07-27 12:41
![image](https://user-images.githubusercontent.com/55085007/88542794-4a718400-d017-11ea-9424-df3a439b989f.png)

**Comment by OlgaKrebs** [comment] 2020-07-27 12:42
![image](https://user-images.githubusercontent.com/55085007/88542832-5eb58100-d017-11ea-8a19-8022ddd01440.png)

**Comment by OlgaKrebs** [comment] 2020-07-27 12:55
I have removed association to Investigation on manage publication page and added it again. Now it worked. 

We need to solve it nevertheless:
1. if associating from investigation page same "warning" about publication type missing should explain to user how to solve that problem.
2. may be it would be good idea to set publication type for all "old" publications to e.g. "journal"

**Comment by matthiaskoenig** [comment] 2020-07-27 20:45
@OlgaKrebs This is a duplicate of #404 which I experienced yesterday.

**Comment by OlgaKrebs** [comment] 2020-07-28 08:42
Yes, Matthias - thanks - I saw your issue after I created this one. But I also found the reason and the way around - this helped Xiaoming to fix the problem (on LySim SEEK first)

**Closed** 2020-07-28 09:57 UTC
