### ISSUE TITLE
Use labels for Galaxy workflow outputs

### ISSUE THREAD

**Issue by simleo** [seek4science/seek#904] opened 2022-02-18 09:14 UTC
See this suggestion by @wm75: https://github.com/galaxyproject/iwc/issues/96

**Comment by wm75** [comment] 2022-02-18 10:56
@fbacall only `workflow_outputs` is what the name suggests. `outputs` is what individual tools produce, but the workflow selects with `workflow_outputs` what's considered relevant in its context.
So for any workflow-centric approach,  `workflow_outputs` is what should be used imo. Would you agree @mvdbeek ?

**Comment by mvdbeek** [comment] 2022-02-18 10:58
Right, those are the top level outputs that are available in reports, as inputs to other subworkflow steps, they're highlighted in the UI, etc.

**Comment by wm75** [comment] 2022-02-18 11:15
> Is there a description of what workflow_outputs is, and whether it will always be present in a .ga file?

Not sure about the first part, but each step in a .ga file will always have `workflow_outputs`. Itss value might be an empty list though if that step does not have any of its `outputs` marked as `workflow_outputs` by the creator of the WF.

**Comment by wm75** [comment] 2022-02-18 11:19
That's just a reference to the step's regular output, i.e. it says: the tool output with this name should become a workflow output.

**Comment by wm75** [comment] 2022-02-18 11:21
I think it's ok if that's parsed/displayed as the Name of the output in workflowhub since there isn't any readily available better alternative.

**Comment by fbacall** [comment] 2022-02-18 11:38
OK so `label` will be the "ID", `output_name` will be the "Name". Do `workflow_outputs` ever have a `type` field like `outputs` do?

**Comment by wm75** [comment] 2022-02-18 11:41
No, that would just be redundant with the info in `outputs`.

**Comment by fbacall** [comment] 2022-02-18 11:45
OK I'm confused then, because it seems sometimes there is no matching entry under `outputs` for an entry in `workflow_outputs`, e.g.
```json
{
  "annotation": "Allele Frequency Filter. This is the minimum allele frequency required for variants to be included in the reports.",
  "content_id": null,
  "errors": null,
  "id": 0,
  "input_connections": {},
  "inputs": [
    {
      "description": "Allele Frequency Filter. This is the minimum allele frequency required for variants to be included in the reports.",
      "name": "AF Filter"
    }
  ],
  "label": "AF Filter",
  "name": "Input parameter",
  "outputs": [],
  "position": {
    "bottom": 414.7942708333333,
    "height": 46.3359375,
    "left": -421.578125,
    "right": -271.578125,
    "top": 368.4583333333333,
    "width": 150,
    "x": -421.578125,
    "y": 368.4583333333333
  },
  "tool_id": null,
  "tool_state": "{\"default\": 0.05, \"parameter_type\": \"float\", \"optional\": true}",
  "tool_version": null,
  "type": "parameter_input",
  "uuid": "2e5a5b38-c204-45a2-98e2-e113bce5a14b",
  "workflow_outputs": [
    {
      "label": null,
      "output_name": "output",
      "uuid": "e55d47c5-7ea0-45c4-8844-47bf29b88542"
    }
  ]
}
```

**Comment by mvdbeek** [comment] 2022-02-18 11:50
Not a bug, inputs are outputs.

**Comment by fbacall** [comment] 2022-02-18 12:12
how does this look?

![image](https://user-images.githubusercontent.com/503373/154680836-1fd63a09-95c7-4bb5-a5eb-9733aa397921.png)

**Comment by wm75** [comment] 2022-02-18 12:17
Minor complications are:
- you don't have the output_name listed for steps with just a single tool output (like '6', '9', '10' in the above)
- it's actually harder to recognize the WF outputs that are in fact input params (in the above it's easy because they are lacking labels - which they shouldn't - so they are the _anonymous_outputs)
-

**Comment by wm75** [comment] 2022-02-18 12:22
One more related thing I just spotted on workflowhub:

![Screenshot from 2022-02-18 13-19-51](https://user-images.githubusercontent.com/4742081/154681990-37a62e85-9cac-4244-9718-2da03ed23f0e.png)

In the steps section you're repeating the Input Params. So like for the workflow outputs, you would probably want to ignore steps with `"type": "parameter_input"`.

**Closed** 2022-03-08 18:07 UTC
