### ISSUE TITLE
Gatekeeper can't see assets to approve

### ISSUE THREAD

**Issue by rabuono** [seek4science/seek#1110] opened 2022-07-20 09:01 UTC
**Describe the bug**
Assets waiting for approval of a gatekeeper do not show for approval.

**To Reproduce**
User1 is the gatekeeper of the Project.
User2 creates an asset (an Investigation), sets it to be public, and gets warned that the gatekeeper needs to approve it before the Investigation is set to public. Meanwhile, Investigation is kept at high privacy (visible only to Project members, but not managed by anyone other than User2).
User1 can't see any assets to be approved, while User2 sees the asset waiting to be approved.

**Expected behavior**
Assets waiting for approval are displayed on the `waiting_approval_assets` page, and can be approved.

**Screenshots**
![image](https://user-images.githubusercontent.com/77321541/179942057-5e5fe253-27cf-4c24-9dcd-45105ecc761d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser Chrome and Firefox
 - SEEK at testing instance: v.1.13.0-master

**Comment by floradanna** [comment] 2022-07-20 09:15
Related to this, in DataHub test instance the following behaviour happens:

Bob (project admin) can click to make his Investigation Public even if Alice is the Gatekeeper of the project, without any warning message. However, the Investigation remains private without any warning message and Alice doesn't receive any notification about this. See screencast below.

https://user-images.githubusercontent.com/51486716/179945023-c10ffec9-ba08-4566-bce0-9ecc28153ad4.mov

**Comment by fbacall** [comment] 2022-07-20 12:47
@rabuono the screenshot you posted for User1 is for the "Assets awaiting approval" page, which shows assets that user has submitted for gatekeeper approval. Requests for publishing would show up on the "Assets you are Gatekeeping" page

![image](https://user-images.githubusercontent.com/503373/179985677-c2aca0ac-74c7-43aa-b8ba-31133e805cba.png)

**Comment by rabuono** [comment] 2022-07-20 13:28
@fbacall You are correct. Sorry. Silly mistake.

I went back in and clicked the correct button and go to approve the Investigation.
However, the Project has a full sharing default policy.
![image](https://user-images.githubusercontent.com/77321541/179992243-46899738-c22f-477f-b142-5986da02bc1b.png)

But the approved Investigation only got partial sharing
![image](https://user-images.githubusercontent.com/77321541/179992342-afece2f5-2348-452f-9750-674d65550894.png)



Also, I went back in and, in single page, created a Study and a Sample inside that Study.
![image](https://user-images.githubusercontent.com/77321541/179993885-cc0c91d5-8b4e-4016-ad69-c7042f9a55a8.png)

These don't show in `/requested_approval_assets` or `/waiting_approval_assets`
![image](https://user-images.githubusercontent.com/77321541/179994060-93a72aef-83bf-4fe6-8af0-3026cfa2d66b.png)

**Comment by fbacall** [comment] 2022-07-20 13:41
Gatekeeper approval only affects the "Public" access level.  In this case it also has "Download" permissions, but it does not show because its an Investigation.

A bug/feature here seems to be that when a new asset is waiting to be approved, it gets given a generic "projects" policy (Projects can view/download, private to everyone else), rather than what the user requested (probably the project's default policy in this case):
https://github.com/seek4science/seek/blob/1766ea842daac4f9c212a5101f47d849e4cd7df1/lib/seek/permissions/publishing_permissions.rb#L123-L132

It should probably be changed to set the policy to what the user requested, except with the "Public" permission set to "No access".

**Comment by rabuono** [comment] 2022-07-20 13:46
> A bug/feature here seems to be that when a new asset is waiting to be approved, it gets given a generic "projects" policy (Projects can view/download, private to everyone else), rather than what the user requested (probably the project's default policy in this case):

Indeed. Giving it what was requested by the Project Admin makes more sense and is the expected behavior. Can we get the more expected behavior of respecting the default sharing policy of the Project upon approval by the gatekeeper? 


But also, Assets made through Single Page don't seem to be showing at `/requested_approval_assets`

**Comment by vdkkia** [comment] 2022-07-20 15:19
> 

I think it was because of some inconsistent assets at the moment caused by an issue that was fixed.
I tried to reproduce the issue but was unsuccessful. So it's working fine.

**Comment by rabuono** [comment] 2022-07-22 13:38
It seems that Samples, created through SEEK's default Sample creation, also do not show up in the gatekeeper's list for approval.
A screenshot showing the gatekeeper warning message, and underneath the original Sample sharing permission of all public:
![image](https://user-images.githubusercontent.com/77321541/180450502-6d546c68-e319-4de2-b494-fea7684f7d24.png)

A screenshot of the modified sharing permissions for the Sample due to the gatekeeper feature:
![image](https://user-images.githubusercontent.com/77321541/180450745-37462fb3-f014-413d-bf9e-18276c13cf04.png)

A screenshot of the created Sample not showing in the gatekeeper's list:
![image](https://user-images.githubusercontent.com/77321541/180450600-63115577-845c-47b8-8b2b-26b4ec06eb46.png)

**Comment by rabuono** [comment] 2022-07-22 13:42
So maybe best is to:

- [ ] Set Gatekeeper to only affect the permissions related to the `Public`
- [ ] Set the assets created trough Single Page to also show up in the Gatekeeper list, when a gatekeeper is assigned and a non-gatekeeper tries to set an asset as public by hand or by a Project default sharing policy
- [ ] Make Samples also appear in the Gatekeeper `requested_approval_assets` list when when a gatekeeper is assigned and a non-gatekeeper tries to set a Sample as public by hand or by a Project default sharing policy

**Comment by whomingbird** [comment] 2022-09-19 10:58
I am trying to reproduce the issue on branch `seek-1.12 `, it seems no problem of showing assets which are waiting for approval. 
![image](https://user-images.githubusercontent.com/42063448/191002517-fed583de-e4fb-4361-9dd3-44a107445f7b.png)


![image](https://user-images.githubusercontent.com/42063448/191002666-b3721986-292c-4114-b65e-fd48313989ae.png)

**Comment by whomingbird** [comment] 2022-09-19 11:14
I just realised that "Gatekeeper function improvement #939" has only been merged to `seek-1.12` branch but not `master` branch.

**Comment by whomingbird** [comment] 2022-09-19 11:27
When i read all the following comments, i realised that the issue is different from what described at the top...  It is more than a bug.

**Comment by rabuono** [comment] 2022-09-19 11:31
@whomingbird Thanks for checking!
It does end up in the three items mentioned at the [earlier comment](https://github.com/seek4science/seek/issues/1110#issuecomment-1192588899).

Samples seem to be problematic regardless of when being created through Single Page or Default view.

**Closed** 2023-06-16 08:31 UTC
Labels: bug, gatekeeper
